package scopeProto;

//Generated by the protocol buffer compiler.  DO NOT EDIT!
//source: AccidentAnalysisClassificationAssistanceTypeProto.proto

public final class AccidentAnalysisClassificationAssistanceTypeProto {
private AccidentAnalysisClassificationAssistanceTypeProto() {}
public static void registerAllExtensions(
   com.google.protobuf.ExtensionRegistry registry) {
}
/**
* Protobuf enum {@code AccidentAnalysisClassificationAssistanceType}
*
* <pre>
* The accident analysis classification assistance type
* </pre>
*/
public enum AccidentAnalysisClassificationAssistanceType
   implements com.google.protobuf.ProtocolMessageEnum {
 /**
  * <code>ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_NOTHING = 0;</code>
  *
  * <pre>
  * Nothing
  * </pre>
  */
 ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_NOTHING(0, 0),
 /**
  * <code>ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_CALL = 1;</code>
  *
  * <pre>
  * Call
  * </pre>
  */
 ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_CALL(1, 1),
 /**
  * <code>ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_AMBULANCE = 2;</code>
  *
  * <pre>
  * Ambulance
  * </pre>
  */
 ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_AMBULANCE(2, 2),
 ;

 /**
  * <code>ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_NOTHING = 0;</code>
  *
  * <pre>
  * Nothing
  * </pre>
  */
 public static final int ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_NOTHING_VALUE = 0;
 /**
  * <code>ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_CALL = 1;</code>
  *
  * <pre>
  * Call
  * </pre>
  */
 public static final int ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_CALL_VALUE = 1;
 /**
  * <code>ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_AMBULANCE = 2;</code>
  *
  * <pre>
  * Ambulance
  * </pre>
  */
 public static final int ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_AMBULANCE_VALUE = 2;


 public final int getNumber() { return value; }

 public static AccidentAnalysisClassificationAssistanceType valueOf(int value) {
   switch (value) {
     case 0: return ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_NOTHING;
     case 1: return ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_CALL;
     case 2: return ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_AMBULANCE;
     default: return null;
   }
 }

 public static com.google.protobuf.Internal.EnumLiteMap<AccidentAnalysisClassificationAssistanceType>
     internalGetValueMap() {
   return internalValueMap;
 }
 private static com.google.protobuf.Internal.EnumLiteMap<AccidentAnalysisClassificationAssistanceType>
     internalValueMap =
       new com.google.protobuf.Internal.EnumLiteMap<AccidentAnalysisClassificationAssistanceType>() {
         public AccidentAnalysisClassificationAssistanceType findValueByNumber(int number) {
           return AccidentAnalysisClassificationAssistanceType.valueOf(number);
         }
       };

 public final com.google.protobuf.Descriptors.EnumValueDescriptor
     getValueDescriptor() {
   return getDescriptor().getValues().get(index);
 }
 public final com.google.protobuf.Descriptors.EnumDescriptor
     getDescriptorForType() {
   return getDescriptor();
 }
 public static final com.google.protobuf.Descriptors.EnumDescriptor
     getDescriptor() {
   return AccidentAnalysisClassificationAssistanceTypeProto.getDescriptor().getEnumTypes().get(0);
 }

 private static final AccidentAnalysisClassificationAssistanceType[] VALUES = values();

 public static AccidentAnalysisClassificationAssistanceType valueOf(
     com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
   if (desc.getType() != getDescriptor()) {
     throw new java.lang.IllegalArgumentException(
       "EnumValueDescriptor is not for this type.");
   }
   return VALUES[desc.getIndex()];
 }

 private final int index;
 private final int value;

 private AccidentAnalysisClassificationAssistanceType(int index, int value) {
   this.index = index;
   this.value = value;
 }

 // @@protoc_insertion_point(enum_scope:AccidentAnalysisClassificationAssistanceType)
}


public static com.google.protobuf.Descriptors.FileDescriptor
   getDescriptor() {
 return descriptor;
}
private static com.google.protobuf.Descriptors.FileDescriptor
   descriptor;
static {
 java.lang.String[] descriptorData = {
   "\n7AccidentAnalysisClassificationAssistan" +
   "ceTypeProto.proto*\330\001\n,AccidentAnalysisCl" +
   "assificationAssistanceType\0227\n3ACCIDENT_A" +
   "NALYSIS_CLASSIFICATION_ASSISTANCE_NOTHIN" +
   "G\020\000\0224\n0ACCIDENT_ANALYSIS_CLASSIFICATION_" +
   "ASSISTANCE_CALL\020\001\0229\n5ACCIDENT_ANALYSIS_C" +
   "LASSIFICATION_ASSISTANCE_AMBULANCE\020\002"
 };
 com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
     new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
       public com.google.protobuf.ExtensionRegistry assignDescriptors(
           com.google.protobuf.Descriptors.FileDescriptor root) {
         descriptor = root;
         return null;
       }
     };
 com.google.protobuf.Descriptors.FileDescriptor
   .internalBuildGeneratedFileFrom(descriptorData,
     new com.google.protobuf.Descriptors.FileDescriptor[] {
     }, assigner);
}

// @@protoc_insertion_point(outer_class_scope)
}
