package scopeProto;

//Generated by the protocol buffer compiler.  DO NOT EDIT!
//source: BluetoothLowEnergyIOReasonTypeProto.proto

public final class BluetoothLowEnergyIOReasonTypeProto {
private BluetoothLowEnergyIOReasonTypeProto() {}
public static void registerAllExtensions(
   com.google.protobuf.ExtensionRegistry registry) {
}
/**
* Protobuf enum {@code BluetoothLowEnergyIOReasonType}
*
* <pre>
* The reason why BluetoothLowEnergyIO event is being sent
* </pre>
*/
public enum BluetoothLowEnergyIOReasonType
   implements com.google.protobuf.ProtocolMessageEnum {
 /**
  * <code>BLUETOOTH_LOW_ENERGY_IO_REASON_UNDEFINED = 0;</code>
  *
  * <pre>
  * Undefined
  * </pre>
  */
 BLUETOOTH_LOW_ENERGY_IO_REASON_UNDEFINED(0, 0),
 /**
  * <code>BLUETOOTH_LOW_ENERGY_IO_REASON_INPUT_CHANGED = 3;</code>
  *
  * <pre>
  * Input changed
  * </pre>
  */
 BLUETOOTH_LOW_ENERGY_IO_REASON_INPUT_CHANGED(1, 3),
 /**
  * <code>BLUETOOTH_LOW_ENERGY_IO_REASON_OUTPUT_CHANGED = 4;</code>
  *
  * <pre>
  * Output changed
  * </pre>
  */
 BLUETOOTH_LOW_ENERGY_IO_REASON_OUTPUT_CHANGED(2, 4),
 /**
  * <code>BLUETOOTH_LOW_ENERGY_IO_REASON_ACCELEROMETER_CHANGED = 5;</code>
  *
  * <pre>
  * Accelerometer changed
  * </pre>
  */
 BLUETOOTH_LOW_ENERGY_IO_REASON_ACCELEROMETER_CHANGED(3, 5),
 /**
  * <code>BLUETOOTH_LOW_ENERGY_IO_REASON_MOVEMENT_DETECTED = 6;</code>
  *
  * <pre>
  * Movement detected
  * </pre>
  */
 BLUETOOTH_LOW_ENERGY_IO_REASON_MOVEMENT_DETECTED(4, 6),
 /**
  * <code>BLUETOOTH_LOW_ENERGY_IO_REASON_EXCESSIVE_SHOCK_DETECTED = 7;</code>
  *
  * <pre>
  * Excessive shock detected
  * </pre>
  */
 BLUETOOTH_LOW_ENERGY_IO_REASON_EXCESSIVE_SHOCK_DETECTED(5, 7),
 /**
  * <code>BLUETOOTH_LOW_ENERGY_IO_REASON_FALL_DETECTED = 8;</code>
  *
  * <pre>
  * Fall detected 
  * </pre>
  */
 BLUETOOTH_LOW_ENERGY_IO_REASON_FALL_DETECTED(6, 8),
 /**
  * <code>BLUETOOTH_LOW_ENERGY_IO_REASON_DOUBLE_TAP_DETECTED = 9;</code>
  *
  * <pre>
  * Double tap detected
  * </pre>
  */
 BLUETOOTH_LOW_ENERGY_IO_REASON_DOUBLE_TAP_DETECTED(7, 9),
 ;

 /**
  * <code>BLUETOOTH_LOW_ENERGY_IO_REASON_UNDEFINED = 0;</code>
  *
  * <pre>
  * Undefined
  * </pre>
  */
 public static final int BLUETOOTH_LOW_ENERGY_IO_REASON_UNDEFINED_VALUE = 0;
 /**
  * <code>BLUETOOTH_LOW_ENERGY_IO_REASON_INPUT_CHANGED = 3;</code>
  *
  * <pre>
  * Input changed
  * </pre>
  */
 public static final int BLUETOOTH_LOW_ENERGY_IO_REASON_INPUT_CHANGED_VALUE = 3;
 /**
  * <code>BLUETOOTH_LOW_ENERGY_IO_REASON_OUTPUT_CHANGED = 4;</code>
  *
  * <pre>
  * Output changed
  * </pre>
  */
 public static final int BLUETOOTH_LOW_ENERGY_IO_REASON_OUTPUT_CHANGED_VALUE = 4;
 /**
  * <code>BLUETOOTH_LOW_ENERGY_IO_REASON_ACCELEROMETER_CHANGED = 5;</code>
  *
  * <pre>
  * Accelerometer changed
  * </pre>
  */
 public static final int BLUETOOTH_LOW_ENERGY_IO_REASON_ACCELEROMETER_CHANGED_VALUE = 5;
 /**
  * <code>BLUETOOTH_LOW_ENERGY_IO_REASON_MOVEMENT_DETECTED = 6;</code>
  *
  * <pre>
  * Movement detected
  * </pre>
  */
 public static final int BLUETOOTH_LOW_ENERGY_IO_REASON_MOVEMENT_DETECTED_VALUE = 6;
 /**
  * <code>BLUETOOTH_LOW_ENERGY_IO_REASON_EXCESSIVE_SHOCK_DETECTED = 7;</code>
  *
  * <pre>
  * Excessive shock detected
  * </pre>
  */
 public static final int BLUETOOTH_LOW_ENERGY_IO_REASON_EXCESSIVE_SHOCK_DETECTED_VALUE = 7;
 /**
  * <code>BLUETOOTH_LOW_ENERGY_IO_REASON_FALL_DETECTED = 8;</code>
  *
  * <pre>
  * Fall detected 
  * </pre>
  */
 public static final int BLUETOOTH_LOW_ENERGY_IO_REASON_FALL_DETECTED_VALUE = 8;
 /**
  * <code>BLUETOOTH_LOW_ENERGY_IO_REASON_DOUBLE_TAP_DETECTED = 9;</code>
  *
  * <pre>
  * Double tap detected
  * </pre>
  */
 public static final int BLUETOOTH_LOW_ENERGY_IO_REASON_DOUBLE_TAP_DETECTED_VALUE = 9;


 public final int getNumber() { return value; }

 public static BluetoothLowEnergyIOReasonType valueOf(int value) {
   switch (value) {
     case 0: return BLUETOOTH_LOW_ENERGY_IO_REASON_UNDEFINED;
     case 3: return BLUETOOTH_LOW_ENERGY_IO_REASON_INPUT_CHANGED;
     case 4: return BLUETOOTH_LOW_ENERGY_IO_REASON_OUTPUT_CHANGED;
     case 5: return BLUETOOTH_LOW_ENERGY_IO_REASON_ACCELEROMETER_CHANGED;
     case 6: return BLUETOOTH_LOW_ENERGY_IO_REASON_MOVEMENT_DETECTED;
     case 7: return BLUETOOTH_LOW_ENERGY_IO_REASON_EXCESSIVE_SHOCK_DETECTED;
     case 8: return BLUETOOTH_LOW_ENERGY_IO_REASON_FALL_DETECTED;
     case 9: return BLUETOOTH_LOW_ENERGY_IO_REASON_DOUBLE_TAP_DETECTED;
     default: return null;
   }
 }

 public static com.google.protobuf.Internal.EnumLiteMap<BluetoothLowEnergyIOReasonType>
     internalGetValueMap() {
   return internalValueMap;
 }
 private static com.google.protobuf.Internal.EnumLiteMap<BluetoothLowEnergyIOReasonType>
     internalValueMap =
       new com.google.protobuf.Internal.EnumLiteMap<BluetoothLowEnergyIOReasonType>() {
         public BluetoothLowEnergyIOReasonType findValueByNumber(int number) {
           return BluetoothLowEnergyIOReasonType.valueOf(number);
         }
       };

 public final com.google.protobuf.Descriptors.EnumValueDescriptor
     getValueDescriptor() {
   return getDescriptor().getValues().get(index);
 }
 public final com.google.protobuf.Descriptors.EnumDescriptor
     getDescriptorForType() {
   return getDescriptor();
 }
 public static final com.google.protobuf.Descriptors.EnumDescriptor
     getDescriptor() {
   return BluetoothLowEnergyIOReasonTypeProto.getDescriptor().getEnumTypes().get(0);
 }

 private static final BluetoothLowEnergyIOReasonType[] VALUES = values();

 public static BluetoothLowEnergyIOReasonType valueOf(
     com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
   if (desc.getType() != getDescriptor()) {
     throw new java.lang.IllegalArgumentException(
       "EnumValueDescriptor is not for this type.");
   }
   return VALUES[desc.getIndex()];
 }

 private final int index;
 private final int value;

 private BluetoothLowEnergyIOReasonType(int index, int value) {
   this.index = index;
   this.value = value;
 }

 // @@protoc_insertion_point(enum_scope:BluetoothLowEnergyIOReasonType)
}


public static com.google.protobuf.Descriptors.FileDescriptor
   getDescriptor() {
 return descriptor;
}
private static com.google.protobuf.Descriptors.FileDescriptor
   descriptor;
static {
 java.lang.String[] descriptorData = {
   "\n)BluetoothLowEnergyIOReasonTypeProto.pr" +
   "oto*\312\003\n\036BluetoothLowEnergyIOReasonType\022," +
   "\n(BLUETOOTH_LOW_ENERGY_IO_REASON_UNDEFIN" +
   "ED\020\000\0220\n,BLUETOOTH_LOW_ENERGY_IO_REASON_I" +
   "NPUT_CHANGED\020\003\0221\n-BLUETOOTH_LOW_ENERGY_I" +
   "O_REASON_OUTPUT_CHANGED\020\004\0228\n4BLUETOOTH_L" +
   "OW_ENERGY_IO_REASON_ACCELEROMETER_CHANGE" +
   "D\020\005\0224\n0BLUETOOTH_LOW_ENERGY_IO_REASON_MO" +
   "VEMENT_DETECTED\020\006\022;\n7BLUETOOTH_LOW_ENERG" +
   "Y_IO_REASON_EXCESSIVE_SHOCK_DETECTED\020\007\0220",
   "\n,BLUETOOTH_LOW_ENERGY_IO_REASON_FALL_DE" +
   "TECTED\020\010\0226\n2BLUETOOTH_LOW_ENERGY_IO_REAS" +
   "ON_DOUBLE_TAP_DETECTED\020\t"
 };
 com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
     new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
       public com.google.protobuf.ExtensionRegistry assignDescriptors(
           com.google.protobuf.Descriptors.FileDescriptor root) {
         descriptor = root;
         return null;
       }
     };
 com.google.protobuf.Descriptors.FileDescriptor
   .internalBuildGeneratedFileFrom(descriptorData,
     new com.google.protobuf.Descriptors.FileDescriptor[] {
     }, assigner);
}

// @@protoc_insertion_point(outer_class_scope)
}
