package scopeProto;

//Generated by the protocol buffer compiler.  DO NOT EDIT!
//source: BluetoothLowEnergyTrackingReasonTypeProto.proto

public final class BluetoothLowEnergyTrackingReasonTypeProto {
private BluetoothLowEnergyTrackingReasonTypeProto() {}
public static void registerAllExtensions(
   com.google.protobuf.ExtensionRegistry registry) {
}
/**
* Protobuf enum {@code BluetoothLowEnergyTrackingReasonType}
*
* <pre>
* The reason why BluetoothLowEnergyTracking event is being sent
* </pre>
*/
public enum BluetoothLowEnergyTrackingReasonType
   implements com.google.protobuf.ProtocolMessageEnum {
 /**
  * <code>BLUETOOTH_LOW_ENERGY_TRACKING_REASON_UNDEFINED = 0;</code>
  *
  * <pre>
  * Undefined
  * </pre>
  */
 BLUETOOTH_LOW_ENERGY_TRACKING_REASON_UNDEFINED(0, 0),
 /**
  * <code>BLUETOOTH_LOW_ENERGY_TRACKING_REASON_NEW_DEVICE = 1;</code>
  *
  * <pre>
  * New device
  * </pre>
  */
 BLUETOOTH_LOW_ENERGY_TRACKING_REASON_NEW_DEVICE(1, 1),
 /**
  * <code>BLUETOOTH_LOW_ENERGY_TRACKING_REASON_DEVICE_DISAPPEARED = 2;</code>
  *
  * <pre>
  * Device disappeared
  * </pre>
  */
 BLUETOOTH_LOW_ENERGY_TRACKING_REASON_DEVICE_DISAPPEARED(2, 2),
 ;

 /**
  * <code>BLUETOOTH_LOW_ENERGY_TRACKING_REASON_UNDEFINED = 0;</code>
  *
  * <pre>
  * Undefined
  * </pre>
  */
 public static final int BLUETOOTH_LOW_ENERGY_TRACKING_REASON_UNDEFINED_VALUE = 0;
 /**
  * <code>BLUETOOTH_LOW_ENERGY_TRACKING_REASON_NEW_DEVICE = 1;</code>
  *
  * <pre>
  * New device
  * </pre>
  */
 public static final int BLUETOOTH_LOW_ENERGY_TRACKING_REASON_NEW_DEVICE_VALUE = 1;
 /**
  * <code>BLUETOOTH_LOW_ENERGY_TRACKING_REASON_DEVICE_DISAPPEARED = 2;</code>
  *
  * <pre>
  * Device disappeared
  * </pre>
  */
 public static final int BLUETOOTH_LOW_ENERGY_TRACKING_REASON_DEVICE_DISAPPEARED_VALUE = 2;


 public final int getNumber() { return value; }

 public static BluetoothLowEnergyTrackingReasonType valueOf(int value) {
   switch (value) {
     case 0: return BLUETOOTH_LOW_ENERGY_TRACKING_REASON_UNDEFINED;
     case 1: return BLUETOOTH_LOW_ENERGY_TRACKING_REASON_NEW_DEVICE;
     case 2: return BLUETOOTH_LOW_ENERGY_TRACKING_REASON_DEVICE_DISAPPEARED;
     default: return null;
   }
 }

 public static com.google.protobuf.Internal.EnumLiteMap<BluetoothLowEnergyTrackingReasonType>
     internalGetValueMap() {
   return internalValueMap;
 }
 private static com.google.protobuf.Internal.EnumLiteMap<BluetoothLowEnergyTrackingReasonType>
     internalValueMap =
       new com.google.protobuf.Internal.EnumLiteMap<BluetoothLowEnergyTrackingReasonType>() {
         public BluetoothLowEnergyTrackingReasonType findValueByNumber(int number) {
           return BluetoothLowEnergyTrackingReasonType.valueOf(number);
         }
       };

 public final com.google.protobuf.Descriptors.EnumValueDescriptor
     getValueDescriptor() {
   return getDescriptor().getValues().get(index);
 }
 public final com.google.protobuf.Descriptors.EnumDescriptor
     getDescriptorForType() {
   return getDescriptor();
 }
 public static final com.google.protobuf.Descriptors.EnumDescriptor
     getDescriptor() {
   return BluetoothLowEnergyTrackingReasonTypeProto.getDescriptor().getEnumTypes().get(0);
 }

 private static final BluetoothLowEnergyTrackingReasonType[] VALUES = values();

 public static BluetoothLowEnergyTrackingReasonType valueOf(
     com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
   if (desc.getType() != getDescriptor()) {
     throw new java.lang.IllegalArgumentException(
       "EnumValueDescriptor is not for this type.");
   }
   return VALUES[desc.getIndex()];
 }

 private final int index;
 private final int value;

 private BluetoothLowEnergyTrackingReasonType(int index, int value) {
   this.index = index;
   this.value = value;
 }

 // @@protoc_insertion_point(enum_scope:BluetoothLowEnergyTrackingReasonType)
}


public static com.google.protobuf.Descriptors.FileDescriptor
   getDescriptor() {
 return descriptor;
}
private static com.google.protobuf.Descriptors.FileDescriptor
   descriptor;
static {
 java.lang.String[] descriptorData = {
   "\n/BluetoothLowEnergyTrackingReasonTypePr" +
   "oto.proto*\314\001\n$BluetoothLowEnergyTracking" +
   "ReasonType\0222\n.BLUETOOTH_LOW_ENERGY_TRACK" +
   "ING_REASON_UNDEFINED\020\000\0223\n/BLUETOOTH_LOW_" +
   "ENERGY_TRACKING_REASON_NEW_DEVICE\020\001\022;\n7B" +
   "LUETOOTH_LOW_ENERGY_TRACKING_REASON_DEVI" +
   "CE_DISAPPEARED\020\002"
 };
 com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
     new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
       public com.google.protobuf.ExtensionRegistry assignDescriptors(
           com.google.protobuf.Descriptors.FileDescriptor root) {
         descriptor = root;
         return null;
       }
     };
 com.google.protobuf.Descriptors.FileDescriptor
   .internalBuildGeneratedFileFrom(descriptorData,
     new com.google.protobuf.Descriptors.FileDescriptor[] {
     }, assigner);
}

// @@protoc_insertion_point(outer_class_scope)
}
