package scopeProto;

//Generated by the protocol buffer compiler.  DO NOT EDIT!
//source: ConsumptionReasonProto.proto

public final class ConsumptionReasonProto {
private ConsumptionReasonProto() {}
public static void registerAllExtensions(
   com.google.protobuf.ExtensionRegistry registry) {
}
/**
* Protobuf enum {@code ConsumptionReason}
*
* <pre>
* Consumption Reason 
* </pre>
*/
public enum ConsumptionReason
   implements com.google.protobuf.ProtocolMessageEnum {
 /**
  * <code>CONSUMPTION_REASON_CO2_TRIP_END = 1;</code>
  *
  * <pre>
  * CO2 Trip End
  * </pre>
  */
 CONSUMPTION_REASON_CO2_TRIP_END(0, 1),
 ;

 /**
  * <code>CONSUMPTION_REASON_CO2_TRIP_END = 1;</code>
  *
  * <pre>
  * CO2 Trip End
  * </pre>
  */
 public static final int CONSUMPTION_REASON_CO2_TRIP_END_VALUE = 1;


 public final int getNumber() { return value; }

 public static ConsumptionReason valueOf(int value) {
   switch (value) {
     case 1: return CONSUMPTION_REASON_CO2_TRIP_END;
     default: return null;
   }
 }

 public static com.google.protobuf.Internal.EnumLiteMap<ConsumptionReason>
     internalGetValueMap() {
   return internalValueMap;
 }
 private static com.google.protobuf.Internal.EnumLiteMap<ConsumptionReason>
     internalValueMap =
       new com.google.protobuf.Internal.EnumLiteMap<ConsumptionReason>() {
         public ConsumptionReason findValueByNumber(int number) {
           return ConsumptionReason.valueOf(number);
         }
       };

 public final com.google.protobuf.Descriptors.EnumValueDescriptor
     getValueDescriptor() {
   return getDescriptor().getValues().get(index);
 }
 public final com.google.protobuf.Descriptors.EnumDescriptor
     getDescriptorForType() {
   return getDescriptor();
 }
 public static final com.google.protobuf.Descriptors.EnumDescriptor
     getDescriptor() {
   return ConsumptionReasonProto.getDescriptor().getEnumTypes().get(0);
 }

 private static final ConsumptionReason[] VALUES = values();

 public static ConsumptionReason valueOf(
     com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
   if (desc.getType() != getDescriptor()) {
     throw new java.lang.IllegalArgumentException(
       "EnumValueDescriptor is not for this type.");
   }
   return VALUES[desc.getIndex()];
 }

 private final int index;
 private final int value;

 private ConsumptionReason(int index, int value) {
   this.index = index;
   this.value = value;
 }

 // @@protoc_insertion_point(enum_scope:ConsumptionReason)
}


public static com.google.protobuf.Descriptors.FileDescriptor
   getDescriptor() {
 return descriptor;
}
private static com.google.protobuf.Descriptors.FileDescriptor
   descriptor;
static {
 java.lang.String[] descriptorData = {
   "\n\034ConsumptionReasonProto.proto*8\n\021Consum" +
   "ptionReason\022#\n\037CONSUMPTION_REASON_CO2_TR" +
   "IP_END\020\001"
 };
 com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
     new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
       public com.google.protobuf.ExtensionRegistry assignDescriptors(
           com.google.protobuf.Descriptors.FileDescriptor root) {
         descriptor = root;
         return null;
       }
     };
 com.google.protobuf.Descriptors.FileDescriptor
   .internalBuildGeneratedFileFrom(descriptorData,
     new com.google.protobuf.Descriptors.FileDescriptor[] {
     }, assigner);
}

// @@protoc_insertion_point(outer_class_scope)
}
