package scopeProto;

//Generated by the protocol buffer compiler.  DO NOT EDIT!
//source: ConsumptionFuelTypeProto.proto

public final class ConsumptionFuelTypeProto {
private ConsumptionFuelTypeProto() {}
public static void registerAllExtensions(
   com.google.protobuf.ExtensionRegistry registry) {
}
/**
* Protobuf enum {@code ConsumptionFuelType}
*
* <pre>
* Consumption fuel type 
* </pre>
*/
public enum ConsumptionFuelType
   implements com.google.protobuf.ProtocolMessageEnum {
 /**
  * <code>CONSUMPTION_FUEL_TYPE_PETROL = 0;</code>
  *
  * <pre>
  * Petrol
  * </pre>
  */
 CONSUMPTION_FUEL_TYPE_PETROL(0, 0),
 /**
  * <code>CONSUMPTION_FUEL_TYPE_DIESEL = 1;</code>
  *
  * <pre>
  * Diesel
  * </pre>
  */
 CONSUMPTION_FUEL_TYPE_DIESEL(1, 1),
 /**
  * <code>CONSUMPTION_FUEL_TYPE_LPGAS = 2;</code>
  *
  * <pre>
  * LP Gas
  * </pre>
  */
 CONSUMPTION_FUEL_TYPE_LPGAS(2, 2),
 ;

 /**
  * <code>CONSUMPTION_FUEL_TYPE_PETROL = 0;</code>
  *
  * <pre>
  * Petrol
  * </pre>
  */
 public static final int CONSUMPTION_FUEL_TYPE_PETROL_VALUE = 0;
 /**
  * <code>CONSUMPTION_FUEL_TYPE_DIESEL = 1;</code>
  *
  * <pre>
  * Diesel
  * </pre>
  */
 public static final int CONSUMPTION_FUEL_TYPE_DIESEL_VALUE = 1;
 /**
  * <code>CONSUMPTION_FUEL_TYPE_LPGAS = 2;</code>
  *
  * <pre>
  * LP Gas
  * </pre>
  */
 public static final int CONSUMPTION_FUEL_TYPE_LPGAS_VALUE = 2;


 public final int getNumber() { return value; }

 public static ConsumptionFuelType valueOf(int value) {
   switch (value) {
     case 0: return CONSUMPTION_FUEL_TYPE_PETROL;
     case 1: return CONSUMPTION_FUEL_TYPE_DIESEL;
     case 2: return CONSUMPTION_FUEL_TYPE_LPGAS;
     default: return null;
   }
 }

 public static com.google.protobuf.Internal.EnumLiteMap<ConsumptionFuelType>
     internalGetValueMap() {
   return internalValueMap;
 }
 private static com.google.protobuf.Internal.EnumLiteMap<ConsumptionFuelType>
     internalValueMap =
       new com.google.protobuf.Internal.EnumLiteMap<ConsumptionFuelType>() {
         public ConsumptionFuelType findValueByNumber(int number) {
           return ConsumptionFuelType.valueOf(number);
         }
       };

 public final com.google.protobuf.Descriptors.EnumValueDescriptor
     getValueDescriptor() {
   return getDescriptor().getValues().get(index);
 }
 public final com.google.protobuf.Descriptors.EnumDescriptor
     getDescriptorForType() {
   return getDescriptor();
 }
 public static final com.google.protobuf.Descriptors.EnumDescriptor
     getDescriptor() {
   return ConsumptionFuelTypeProto.getDescriptor().getEnumTypes().get(0);
 }

 private static final ConsumptionFuelType[] VALUES = values();

 public static ConsumptionFuelType valueOf(
     com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
   if (desc.getType() != getDescriptor()) {
     throw new java.lang.IllegalArgumentException(
       "EnumValueDescriptor is not for this type.");
   }
   return VALUES[desc.getIndex()];
 }

 private final int index;
 private final int value;

 private ConsumptionFuelType(int index, int value) {
   this.index = index;
   this.value = value;
 }

 // @@protoc_insertion_point(enum_scope:ConsumptionFuelType)
}


public static com.google.protobuf.Descriptors.FileDescriptor
   getDescriptor() {
 return descriptor;
}
private static com.google.protobuf.Descriptors.FileDescriptor
   descriptor;
static {
 java.lang.String[] descriptorData = {
   "\n\036ConsumptionFuelTypeProto.proto*z\n\023Cons" +
   "umptionFuelType\022 \n\034CONSUMPTION_FUEL_TYPE" +
   "_PETROL\020\000\022 \n\034CONSUMPTION_FUEL_TYPE_DIESE" +
   "L\020\001\022\037\n\033CONSUMPTION_FUEL_TYPE_LPGAS\020\002"
 };
 com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
     new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
       public com.google.protobuf.ExtensionRegistry assignDescriptors(
           com.google.protobuf.Descriptors.FileDescriptor root) {
         descriptor = root;
         return null;
       }
     };
 com.google.protobuf.Descriptors.FileDescriptor
   .internalBuildGeneratedFileFrom(descriptorData,
     new com.google.protobuf.Descriptors.FileDescriptor[] {
     }, assigner);
}

// @@protoc_insertion_point(outer_class_scope)
}
