package scopeProto;

//Generated by the protocol buffer compiler.  DO NOT EDIT!
//source: DailyGeofenceSummaryProto.proto

public final class DailyGeofenceSummaryProto {
private DailyGeofenceSummaryProto() {}
public static void registerAllExtensions(
   com.google.protobuf.ExtensionRegistry registry) {
}
public interface DailyGeofenceSummaryOrBuilder extends
   // @@protoc_insertion_point(interface_extends:DailyGeofenceSummary)
   com.google.protobuf.MessageOrBuilder {

 /**
  * <code>required .EventHeader header = 1;</code>
  */
 boolean hasHeader();
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 EventHeaderProto.EventHeader getHeader();
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 EventHeaderProto.EventHeaderOrBuilder getHeaderOrBuilder();

 /**
  * <code>optional uint32 geofence_type1_entries = 2;</code>
  *
  * <pre>
  * Geofence type 1 entries
  * </pre>
  */
 boolean hasGeofenceType1Entries();
 /**
  * <code>optional uint32 geofence_type1_entries = 2;</code>
  *
  * <pre>
  * Geofence type 1 entries
  * </pre>
  */
 int getGeofenceType1Entries();

 /**
  * <code>optional uint32 geofence_type1_time = 3;</code>
  *
  * <pre>
  * Geofence type 1 time (seconds)
  * </pre>
  */
 boolean hasGeofenceType1Time();
 /**
  * <code>optional uint32 geofence_type1_time = 3;</code>
  *
  * <pre>
  * Geofence type 1 time (seconds)
  * </pre>
  */
 int getGeofenceType1Time();

 /**
  * <code>optional uint32 geofence_type1_distance = 4;</code>
  *
  * <pre>
  * Geofence type 1 distance (meters)
  * </pre>
  */
 boolean hasGeofenceType1Distance();
 /**
  * <code>optional uint32 geofence_type1_distance = 4;</code>
  *
  * <pre>
  * Geofence type 1 distance (meters)
  * </pre>
  */
 int getGeofenceType1Distance();

 /**
  * <code>optional uint32 geofence_type2_entries = 5;</code>
  *
  * <pre>
  * Geofence type 2 entries
  * </pre>
  */
 boolean hasGeofenceType2Entries();
 /**
  * <code>optional uint32 geofence_type2_entries = 5;</code>
  *
  * <pre>
  * Geofence type 2 entries
  * </pre>
  */
 int getGeofenceType2Entries();

 /**
  * <code>optional uint32 geofence_type2_time = 6;</code>
  *
  * <pre>
  * Geofence type 2 time (seconds)
  * </pre>
  */
 boolean hasGeofenceType2Time();
 /**
  * <code>optional uint32 geofence_type2_time = 6;</code>
  *
  * <pre>
  * Geofence type 2 time (seconds)
  * </pre>
  */
 int getGeofenceType2Time();

 /**
  * <code>optional uint32 geofence_type2_distance = 7;</code>
  *
  * <pre>
  * Geofence type 2 distance (meters)
  * </pre>
  */
 boolean hasGeofenceType2Distance();
 /**
  * <code>optional uint32 geofence_type2_distance = 7;</code>
  *
  * <pre>
  * Geofence type 2 distance (meters)
  * </pre>
  */
 int getGeofenceType2Distance();
}
/**
* Protobuf type {@code DailyGeofenceSummary}
*
* <pre>
* Daily geofence summary
* </pre>
*/
public static final class DailyGeofenceSummary extends
   com.google.protobuf.GeneratedMessage implements
   // @@protoc_insertion_point(message_implements:DailyGeofenceSummary)
   DailyGeofenceSummaryOrBuilder {
 // Use DailyGeofenceSummary.newBuilder() to construct.
 private DailyGeofenceSummary(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
   super(builder);
   this.unknownFields = builder.getUnknownFields();
 }
 private DailyGeofenceSummary(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

 private static final DailyGeofenceSummary defaultInstance;
 public static DailyGeofenceSummary getDefaultInstance() {
   return defaultInstance;
 }

 public DailyGeofenceSummary getDefaultInstanceForType() {
   return defaultInstance;
 }

 private final com.google.protobuf.UnknownFieldSet unknownFields;
 @java.lang.Override
 public final com.google.protobuf.UnknownFieldSet
     getUnknownFields() {
   return this.unknownFields;
 }
 private DailyGeofenceSummary(
     com.google.protobuf.CodedInputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   initFields();
   int mutable_bitField0_ = 0;
   com.google.protobuf.UnknownFieldSet.Builder unknownFields =
       com.google.protobuf.UnknownFieldSet.newBuilder();
   try {
     boolean done = false;
     while (!done) {
       int tag = input.readTag();
       switch (tag) {
         case 0:
           done = true;
           break;
         default: {
           if (!parseUnknownField(input, unknownFields,
                                  extensionRegistry, tag)) {
             done = true;
           }
           break;
         }
         case 10: {
           EventHeaderProto.EventHeader.Builder subBuilder = null;
           if (((bitField0_ & 0x00000001) == 0x00000001)) {
             subBuilder = header_.toBuilder();
           }
           header_ = input.readMessage(EventHeaderProto.EventHeader.PARSER, extensionRegistry);
           if (subBuilder != null) {
             subBuilder.mergeFrom(header_);
             header_ = subBuilder.buildPartial();
           }
           bitField0_ |= 0x00000001;
           break;
         }
         case 16: {
           bitField0_ |= 0x00000002;
           geofenceType1Entries_ = input.readUInt32();
           break;
         }
         case 24: {
           bitField0_ |= 0x00000004;
           geofenceType1Time_ = input.readUInt32();
           break;
         }
         case 32: {
           bitField0_ |= 0x00000008;
           geofenceType1Distance_ = input.readUInt32();
           break;
         }
         case 40: {
           bitField0_ |= 0x00000010;
           geofenceType2Entries_ = input.readUInt32();
           break;
         }
         case 48: {
           bitField0_ |= 0x00000020;
           geofenceType2Time_ = input.readUInt32();
           break;
         }
         case 56: {
           bitField0_ |= 0x00000040;
           geofenceType2Distance_ = input.readUInt32();
           break;
         }
       }
     }
   } catch (com.google.protobuf.InvalidProtocolBufferException e) {
     throw e.setUnfinishedMessage(this);
   } catch (java.io.IOException e) {
     throw new com.google.protobuf.InvalidProtocolBufferException(
         e.getMessage()).setUnfinishedMessage(this);
   } finally {
     this.unknownFields = unknownFields.build();
     makeExtensionsImmutable();
   }
 }
 public static final com.google.protobuf.Descriptors.Descriptor
     getDescriptor() {
   return DailyGeofenceSummaryProto.internal_static_DailyGeofenceSummary_descriptor;
 }

 protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
     internalGetFieldAccessorTable() {
   return DailyGeofenceSummaryProto.internal_static_DailyGeofenceSummary_fieldAccessorTable
       .ensureFieldAccessorsInitialized(
           DailyGeofenceSummaryProto.DailyGeofenceSummary.class, DailyGeofenceSummaryProto.DailyGeofenceSummary.Builder.class);
 }

 public static com.google.protobuf.Parser<DailyGeofenceSummary> PARSER =
     new com.google.protobuf.AbstractParser<DailyGeofenceSummary>() {
   public DailyGeofenceSummary parsePartialFrom(
       com.google.protobuf.CodedInputStream input,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws com.google.protobuf.InvalidProtocolBufferException {
     return new DailyGeofenceSummary(input, extensionRegistry);
   }
 };

 @java.lang.Override
 public com.google.protobuf.Parser<DailyGeofenceSummary> getParserForType() {
   return PARSER;
 }

 private int bitField0_;
 public static final int HEADER_FIELD_NUMBER = 1;
 private EventHeaderProto.EventHeader header_;
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 public boolean hasHeader() {
   return ((bitField0_ & 0x00000001) == 0x00000001);
 }
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 public EventHeaderProto.EventHeader getHeader() {
   return header_;
 }
 /**
  * <code>required .EventHeader header = 1;</code>
  */
 public EventHeaderProto.EventHeaderOrBuilder getHeaderOrBuilder() {
   return header_;
 }

 public static final int GEOFENCE_TYPE1_ENTRIES_FIELD_NUMBER = 2;
 private int geofenceType1Entries_;
 /**
  * <code>optional uint32 geofence_type1_entries = 2;</code>
  *
  * <pre>
  * Geofence type 1 entries
  * </pre>
  */
 public boolean hasGeofenceType1Entries() {
   return ((bitField0_ & 0x00000002) == 0x00000002);
 }
 /**
  * <code>optional uint32 geofence_type1_entries = 2;</code>
  *
  * <pre>
  * Geofence type 1 entries
  * </pre>
  */
 public int getGeofenceType1Entries() {
   return geofenceType1Entries_;
 }

 public static final int GEOFENCE_TYPE1_TIME_FIELD_NUMBER = 3;
 private int geofenceType1Time_;
 /**
  * <code>optional uint32 geofence_type1_time = 3;</code>
  *
  * <pre>
  * Geofence type 1 time (seconds)
  * </pre>
  */
 public boolean hasGeofenceType1Time() {
   return ((bitField0_ & 0x00000004) == 0x00000004);
 }
 /**
  * <code>optional uint32 geofence_type1_time = 3;</code>
  *
  * <pre>
  * Geofence type 1 time (seconds)
  * </pre>
  */
 public int getGeofenceType1Time() {
   return geofenceType1Time_;
 }

 public static final int GEOFENCE_TYPE1_DISTANCE_FIELD_NUMBER = 4;
 private int geofenceType1Distance_;
 /**
  * <code>optional uint32 geofence_type1_distance = 4;</code>
  *
  * <pre>
  * Geofence type 1 distance (meters)
  * </pre>
  */
 public boolean hasGeofenceType1Distance() {
   return ((bitField0_ & 0x00000008) == 0x00000008);
 }
 /**
  * <code>optional uint32 geofence_type1_distance = 4;</code>
  *
  * <pre>
  * Geofence type 1 distance (meters)
  * </pre>
  */
 public int getGeofenceType1Distance() {
   return geofenceType1Distance_;
 }

 public static final int GEOFENCE_TYPE2_ENTRIES_FIELD_NUMBER = 5;
 private int geofenceType2Entries_;
 /**
  * <code>optional uint32 geofence_type2_entries = 5;</code>
  *
  * <pre>
  * Geofence type 2 entries
  * </pre>
  */
 public boolean hasGeofenceType2Entries() {
   return ((bitField0_ & 0x00000010) == 0x00000010);
 }
 /**
  * <code>optional uint32 geofence_type2_entries = 5;</code>
  *
  * <pre>
  * Geofence type 2 entries
  * </pre>
  */
 public int getGeofenceType2Entries() {
   return geofenceType2Entries_;
 }

 public static final int GEOFENCE_TYPE2_TIME_FIELD_NUMBER = 6;
 private int geofenceType2Time_;
 /**
  * <code>optional uint32 geofence_type2_time = 6;</code>
  *
  * <pre>
  * Geofence type 2 time (seconds)
  * </pre>
  */
 public boolean hasGeofenceType2Time() {
   return ((bitField0_ & 0x00000020) == 0x00000020);
 }
 /**
  * <code>optional uint32 geofence_type2_time = 6;</code>
  *
  * <pre>
  * Geofence type 2 time (seconds)
  * </pre>
  */
 public int getGeofenceType2Time() {
   return geofenceType2Time_;
 }

 public static final int GEOFENCE_TYPE2_DISTANCE_FIELD_NUMBER = 7;
 private int geofenceType2Distance_;
 /**
  * <code>optional uint32 geofence_type2_distance = 7;</code>
  *
  * <pre>
  * Geofence type 2 distance (meters)
  * </pre>
  */
 public boolean hasGeofenceType2Distance() {
   return ((bitField0_ & 0x00000040) == 0x00000040);
 }
 /**
  * <code>optional uint32 geofence_type2_distance = 7;</code>
  *
  * <pre>
  * Geofence type 2 distance (meters)
  * </pre>
  */
 public int getGeofenceType2Distance() {
   return geofenceType2Distance_;
 }

 private void initFields() {
   header_ = EventHeaderProto.EventHeader.getDefaultInstance();
   geofenceType1Entries_ = 0;
   geofenceType1Time_ = 0;
   geofenceType1Distance_ = 0;
   geofenceType2Entries_ = 0;
   geofenceType2Time_ = 0;
   geofenceType2Distance_ = 0;
 }
 private byte memoizedIsInitialized = -1;
 public final boolean isInitialized() {
   byte isInitialized = memoizedIsInitialized;
   if (isInitialized == 1) return true;
   if (isInitialized == 0) return false;

   if (!hasHeader()) {
     memoizedIsInitialized = 0;
     return false;
   }
   if (!getHeader().isInitialized()) {
     memoizedIsInitialized = 0;
     return false;
   }
   memoizedIsInitialized = 1;
   return true;
 }

 public void writeTo(com.google.protobuf.CodedOutputStream output)
                     throws java.io.IOException {
   getSerializedSize();
   if (((bitField0_ & 0x00000001) == 0x00000001)) {
     output.writeMessage(1, header_);
   }
   if (((bitField0_ & 0x00000002) == 0x00000002)) {
     output.writeUInt32(2, geofenceType1Entries_);
   }
   if (((bitField0_ & 0x00000004) == 0x00000004)) {
     output.writeUInt32(3, geofenceType1Time_);
   }
   if (((bitField0_ & 0x00000008) == 0x00000008)) {
     output.writeUInt32(4, geofenceType1Distance_);
   }
   if (((bitField0_ & 0x00000010) == 0x00000010)) {
     output.writeUInt32(5, geofenceType2Entries_);
   }
   if (((bitField0_ & 0x00000020) == 0x00000020)) {
     output.writeUInt32(6, geofenceType2Time_);
   }
   if (((bitField0_ & 0x00000040) == 0x00000040)) {
     output.writeUInt32(7, geofenceType2Distance_);
   }
   getUnknownFields().writeTo(output);
 }

 private int memoizedSerializedSize = -1;
 public int getSerializedSize() {
   int size = memoizedSerializedSize;
   if (size != -1) return size;

   size = 0;
   if (((bitField0_ & 0x00000001) == 0x00000001)) {
     size += com.google.protobuf.CodedOutputStream
       .computeMessageSize(1, header_);
   }
   if (((bitField0_ & 0x00000002) == 0x00000002)) {
     size += com.google.protobuf.CodedOutputStream
       .computeUInt32Size(2, geofenceType1Entries_);
   }
   if (((bitField0_ & 0x00000004) == 0x00000004)) {
     size += com.google.protobuf.CodedOutputStream
       .computeUInt32Size(3, geofenceType1Time_);
   }
   if (((bitField0_ & 0x00000008) == 0x00000008)) {
     size += com.google.protobuf.CodedOutputStream
       .computeUInt32Size(4, geofenceType1Distance_);
   }
   if (((bitField0_ & 0x00000010) == 0x00000010)) {
     size += com.google.protobuf.CodedOutputStream
       .computeUInt32Size(5, geofenceType2Entries_);
   }
   if (((bitField0_ & 0x00000020) == 0x00000020)) {
     size += com.google.protobuf.CodedOutputStream
       .computeUInt32Size(6, geofenceType2Time_);
   }
   if (((bitField0_ & 0x00000040) == 0x00000040)) {
     size += com.google.protobuf.CodedOutputStream
       .computeUInt32Size(7, geofenceType2Distance_);
   }
   size += getUnknownFields().getSerializedSize();
   memoizedSerializedSize = size;
   return size;
 }

 private static final long serialVersionUID = 0L;
 @java.lang.Override
 protected java.lang.Object writeReplace()
     throws java.io.ObjectStreamException {
   return super.writeReplace();
 }

 public static DailyGeofenceSummaryProto.DailyGeofenceSummary parseFrom(
     com.google.protobuf.ByteString data)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data);
 }
 public static DailyGeofenceSummaryProto.DailyGeofenceSummary parseFrom(
     com.google.protobuf.ByteString data,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data, extensionRegistry);
 }
 public static DailyGeofenceSummaryProto.DailyGeofenceSummary parseFrom(byte[] data)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data);
 }
 public static DailyGeofenceSummaryProto.DailyGeofenceSummary parseFrom(
     byte[] data,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws com.google.protobuf.InvalidProtocolBufferException {
   return PARSER.parseFrom(data, extensionRegistry);
 }
 public static DailyGeofenceSummaryProto.DailyGeofenceSummary parseFrom(java.io.InputStream input)
     throws java.io.IOException {
   return PARSER.parseFrom(input);
 }
 public static DailyGeofenceSummaryProto.DailyGeofenceSummary parseFrom(
     java.io.InputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return PARSER.parseFrom(input, extensionRegistry);
 }
 public static DailyGeofenceSummaryProto.DailyGeofenceSummary parseDelimitedFrom(java.io.InputStream input)
     throws java.io.IOException {
   return PARSER.parseDelimitedFrom(input);
 }
 public static DailyGeofenceSummaryProto.DailyGeofenceSummary parseDelimitedFrom(
     java.io.InputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return PARSER.parseDelimitedFrom(input, extensionRegistry);
 }
 public static DailyGeofenceSummaryProto.DailyGeofenceSummary parseFrom(
     com.google.protobuf.CodedInputStream input)
     throws java.io.IOException {
   return PARSER.parseFrom(input);
 }
 public static DailyGeofenceSummaryProto.DailyGeofenceSummary parseFrom(
     com.google.protobuf.CodedInputStream input,
     com.google.protobuf.ExtensionRegistryLite extensionRegistry)
     throws java.io.IOException {
   return PARSER.parseFrom(input, extensionRegistry);
 }

 public static Builder newBuilder() { return Builder.create(); }
 public Builder newBuilderForType() { return newBuilder(); }
 public static Builder newBuilder(DailyGeofenceSummaryProto.DailyGeofenceSummary prototype) {
   return newBuilder().mergeFrom(prototype);
 }
 public Builder toBuilder() { return newBuilder(this); }

 @java.lang.Override
 protected Builder newBuilderForType(
     com.google.protobuf.GeneratedMessage.BuilderParent parent) {
   Builder builder = new Builder(parent);
   return builder;
 }
 /**
  * Protobuf type {@code DailyGeofenceSummary}
  *
  * <pre>
  * Daily geofence summary
  * </pre>
  */
 public static final class Builder extends
     com.google.protobuf.GeneratedMessage.Builder<Builder> implements
     // @@protoc_insertion_point(builder_implements:DailyGeofenceSummary)
     DailyGeofenceSummaryProto.DailyGeofenceSummaryOrBuilder {
   public static final com.google.protobuf.Descriptors.Descriptor
       getDescriptor() {
     return DailyGeofenceSummaryProto.internal_static_DailyGeofenceSummary_descriptor;
   }

   protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
       internalGetFieldAccessorTable() {
     return DailyGeofenceSummaryProto.internal_static_DailyGeofenceSummary_fieldAccessorTable
         .ensureFieldAccessorsInitialized(
             DailyGeofenceSummaryProto.DailyGeofenceSummary.class, DailyGeofenceSummaryProto.DailyGeofenceSummary.Builder.class);
   }

   // Construct using DailyGeofenceSummaryProto.DailyGeofenceSummary.newBuilder()
   private Builder() {
     maybeForceBuilderInitialization();
   }

   private Builder(
       com.google.protobuf.GeneratedMessage.BuilderParent parent) {
     super(parent);
     maybeForceBuilderInitialization();
   }
   private void maybeForceBuilderInitialization() {
     if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
       getHeaderFieldBuilder();
     }
   }
   private static Builder create() {
     return new Builder();
   }

   public Builder clear() {
     super.clear();
     if (headerBuilder_ == null) {
       header_ = EventHeaderProto.EventHeader.getDefaultInstance();
     } else {
       headerBuilder_.clear();
     }
     bitField0_ = (bitField0_ & ~0x00000001);
     geofenceType1Entries_ = 0;
     bitField0_ = (bitField0_ & ~0x00000002);
     geofenceType1Time_ = 0;
     bitField0_ = (bitField0_ & ~0x00000004);
     geofenceType1Distance_ = 0;
     bitField0_ = (bitField0_ & ~0x00000008);
     geofenceType2Entries_ = 0;
     bitField0_ = (bitField0_ & ~0x00000010);
     geofenceType2Time_ = 0;
     bitField0_ = (bitField0_ & ~0x00000020);
     geofenceType2Distance_ = 0;
     bitField0_ = (bitField0_ & ~0x00000040);
     return this;
   }

   public Builder clone() {
     return create().mergeFrom(buildPartial());
   }

   public com.google.protobuf.Descriptors.Descriptor
       getDescriptorForType() {
     return DailyGeofenceSummaryProto.internal_static_DailyGeofenceSummary_descriptor;
   }

   public DailyGeofenceSummaryProto.DailyGeofenceSummary getDefaultInstanceForType() {
     return DailyGeofenceSummaryProto.DailyGeofenceSummary.getDefaultInstance();
   }

   public DailyGeofenceSummaryProto.DailyGeofenceSummary build() {
     DailyGeofenceSummaryProto.DailyGeofenceSummary result = buildPartial();
     if (!result.isInitialized()) {
       throw newUninitializedMessageException(result);
     }
     return result;
   }

   public DailyGeofenceSummaryProto.DailyGeofenceSummary buildPartial() {
     DailyGeofenceSummaryProto.DailyGeofenceSummary result = new DailyGeofenceSummaryProto.DailyGeofenceSummary(this);
     int from_bitField0_ = bitField0_;
     int to_bitField0_ = 0;
     if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
       to_bitField0_ |= 0x00000001;
     }
     if (headerBuilder_ == null) {
       result.header_ = header_;
     } else {
       result.header_ = headerBuilder_.build();
     }
     if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
       to_bitField0_ |= 0x00000002;
     }
     result.geofenceType1Entries_ = geofenceType1Entries_;
     if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
       to_bitField0_ |= 0x00000004;
     }
     result.geofenceType1Time_ = geofenceType1Time_;
     if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
       to_bitField0_ |= 0x00000008;
     }
     result.geofenceType1Distance_ = geofenceType1Distance_;
     if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
       to_bitField0_ |= 0x00000010;
     }
     result.geofenceType2Entries_ = geofenceType2Entries_;
     if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
       to_bitField0_ |= 0x00000020;
     }
     result.geofenceType2Time_ = geofenceType2Time_;
     if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
       to_bitField0_ |= 0x00000040;
     }
     result.geofenceType2Distance_ = geofenceType2Distance_;
     result.bitField0_ = to_bitField0_;
     onBuilt();
     return result;
   }

   public Builder mergeFrom(com.google.protobuf.Message other) {
     if (other instanceof DailyGeofenceSummaryProto.DailyGeofenceSummary) {
       return mergeFrom((DailyGeofenceSummaryProto.DailyGeofenceSummary)other);
     } else {
       super.mergeFrom(other);
       return this;
     }
   }

   public Builder mergeFrom(DailyGeofenceSummaryProto.DailyGeofenceSummary other) {
     if (other == DailyGeofenceSummaryProto.DailyGeofenceSummary.getDefaultInstance()) return this;
     if (other.hasHeader()) {
       mergeHeader(other.getHeader());
     }
     if (other.hasGeofenceType1Entries()) {
       setGeofenceType1Entries(other.getGeofenceType1Entries());
     }
     if (other.hasGeofenceType1Time()) {
       setGeofenceType1Time(other.getGeofenceType1Time());
     }
     if (other.hasGeofenceType1Distance()) {
       setGeofenceType1Distance(other.getGeofenceType1Distance());
     }
     if (other.hasGeofenceType2Entries()) {
       setGeofenceType2Entries(other.getGeofenceType2Entries());
     }
     if (other.hasGeofenceType2Time()) {
       setGeofenceType2Time(other.getGeofenceType2Time());
     }
     if (other.hasGeofenceType2Distance()) {
       setGeofenceType2Distance(other.getGeofenceType2Distance());
     }
     this.mergeUnknownFields(other.getUnknownFields());
     return this;
   }

   public final boolean isInitialized() {
     if (!hasHeader()) {
       
       return false;
     }
     if (!getHeader().isInitialized()) {
       
       return false;
     }
     return true;
   }

   public Builder mergeFrom(
       com.google.protobuf.CodedInputStream input,
       com.google.protobuf.ExtensionRegistryLite extensionRegistry)
       throws java.io.IOException {
     DailyGeofenceSummaryProto.DailyGeofenceSummary parsedMessage = null;
     try {
       parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
     } catch (com.google.protobuf.InvalidProtocolBufferException e) {
       parsedMessage = (DailyGeofenceSummaryProto.DailyGeofenceSummary) e.getUnfinishedMessage();
       throw e;
     } finally {
       if (parsedMessage != null) {
         mergeFrom(parsedMessage);
       }
     }
     return this;
   }
   private int bitField0_;

   private EventHeaderProto.EventHeader header_ = EventHeaderProto.EventHeader.getDefaultInstance();
   private com.google.protobuf.SingleFieldBuilder<
       EventHeaderProto.EventHeader, EventHeaderProto.EventHeader.Builder, EventHeaderProto.EventHeaderOrBuilder> headerBuilder_;
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public boolean hasHeader() {
     return ((bitField0_ & 0x00000001) == 0x00000001);
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public EventHeaderProto.EventHeader getHeader() {
     if (headerBuilder_ == null) {
       return header_;
     } else {
       return headerBuilder_.getMessage();
     }
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public Builder setHeader(EventHeaderProto.EventHeader value) {
     if (headerBuilder_ == null) {
       if (value == null) {
         throw new NullPointerException();
       }
       header_ = value;
       onChanged();
     } else {
       headerBuilder_.setMessage(value);
     }
     bitField0_ |= 0x00000001;
     return this;
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public Builder setHeader(
       EventHeaderProto.EventHeader.Builder builderForValue) {
     if (headerBuilder_ == null) {
       header_ = builderForValue.build();
       onChanged();
     } else {
       headerBuilder_.setMessage(builderForValue.build());
     }
     bitField0_ |= 0x00000001;
     return this;
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public Builder mergeHeader(EventHeaderProto.EventHeader value) {
     if (headerBuilder_ == null) {
       if (((bitField0_ & 0x00000001) == 0x00000001) &&
           header_ != EventHeaderProto.EventHeader.getDefaultInstance()) {
         header_ =
           EventHeaderProto.EventHeader.newBuilder(header_).mergeFrom(value).buildPartial();
       } else {
         header_ = value;
       }
       onChanged();
     } else {
       headerBuilder_.mergeFrom(value);
     }
     bitField0_ |= 0x00000001;
     return this;
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public Builder clearHeader() {
     if (headerBuilder_ == null) {
       header_ = EventHeaderProto.EventHeader.getDefaultInstance();
       onChanged();
     } else {
       headerBuilder_.clear();
     }
     bitField0_ = (bitField0_ & ~0x00000001);
     return this;
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public EventHeaderProto.EventHeader.Builder getHeaderBuilder() {
     bitField0_ |= 0x00000001;
     onChanged();
     return getHeaderFieldBuilder().getBuilder();
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   public EventHeaderProto.EventHeaderOrBuilder getHeaderOrBuilder() {
     if (headerBuilder_ != null) {
       return headerBuilder_.getMessageOrBuilder();
     } else {
       return header_;
     }
   }
   /**
    * <code>required .EventHeader header = 1;</code>
    */
   private com.google.protobuf.SingleFieldBuilder<
       EventHeaderProto.EventHeader, EventHeaderProto.EventHeader.Builder, EventHeaderProto.EventHeaderOrBuilder> 
       getHeaderFieldBuilder() {
     if (headerBuilder_ == null) {
       headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
           EventHeaderProto.EventHeader, EventHeaderProto.EventHeader.Builder, EventHeaderProto.EventHeaderOrBuilder>(
               getHeader(),
               getParentForChildren(),
               isClean());
       header_ = null;
     }
     return headerBuilder_;
   }

   private int geofenceType1Entries_ ;
   /**
    * <code>optional uint32 geofence_type1_entries = 2;</code>
    *
    * <pre>
    * Geofence type 1 entries
    * </pre>
    */
   public boolean hasGeofenceType1Entries() {
     return ((bitField0_ & 0x00000002) == 0x00000002);
   }
   /**
    * <code>optional uint32 geofence_type1_entries = 2;</code>
    *
    * <pre>
    * Geofence type 1 entries
    * </pre>
    */
   public int getGeofenceType1Entries() {
     return geofenceType1Entries_;
   }
   /**
    * <code>optional uint32 geofence_type1_entries = 2;</code>
    *
    * <pre>
    * Geofence type 1 entries
    * </pre>
    */
   public Builder setGeofenceType1Entries(int value) {
     bitField0_ |= 0x00000002;
     geofenceType1Entries_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional uint32 geofence_type1_entries = 2;</code>
    *
    * <pre>
    * Geofence type 1 entries
    * </pre>
    */
   public Builder clearGeofenceType1Entries() {
     bitField0_ = (bitField0_ & ~0x00000002);
     geofenceType1Entries_ = 0;
     onChanged();
     return this;
   }

   private int geofenceType1Time_ ;
   /**
    * <code>optional uint32 geofence_type1_time = 3;</code>
    *
    * <pre>
    * Geofence type 1 time (seconds)
    * </pre>
    */
   public boolean hasGeofenceType1Time() {
     return ((bitField0_ & 0x00000004) == 0x00000004);
   }
   /**
    * <code>optional uint32 geofence_type1_time = 3;</code>
    *
    * <pre>
    * Geofence type 1 time (seconds)
    * </pre>
    */
   public int getGeofenceType1Time() {
     return geofenceType1Time_;
   }
   /**
    * <code>optional uint32 geofence_type1_time = 3;</code>
    *
    * <pre>
    * Geofence type 1 time (seconds)
    * </pre>
    */
   public Builder setGeofenceType1Time(int value) {
     bitField0_ |= 0x00000004;
     geofenceType1Time_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional uint32 geofence_type1_time = 3;</code>
    *
    * <pre>
    * Geofence type 1 time (seconds)
    * </pre>
    */
   public Builder clearGeofenceType1Time() {
     bitField0_ = (bitField0_ & ~0x00000004);
     geofenceType1Time_ = 0;
     onChanged();
     return this;
   }

   private int geofenceType1Distance_ ;
   /**
    * <code>optional uint32 geofence_type1_distance = 4;</code>
    *
    * <pre>
    * Geofence type 1 distance (meters)
    * </pre>
    */
   public boolean hasGeofenceType1Distance() {
     return ((bitField0_ & 0x00000008) == 0x00000008);
   }
   /**
    * <code>optional uint32 geofence_type1_distance = 4;</code>
    *
    * <pre>
    * Geofence type 1 distance (meters)
    * </pre>
    */
   public int getGeofenceType1Distance() {
     return geofenceType1Distance_;
   }
   /**
    * <code>optional uint32 geofence_type1_distance = 4;</code>
    *
    * <pre>
    * Geofence type 1 distance (meters)
    * </pre>
    */
   public Builder setGeofenceType1Distance(int value) {
     bitField0_ |= 0x00000008;
     geofenceType1Distance_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional uint32 geofence_type1_distance = 4;</code>
    *
    * <pre>
    * Geofence type 1 distance (meters)
    * </pre>
    */
   public Builder clearGeofenceType1Distance() {
     bitField0_ = (bitField0_ & ~0x00000008);
     geofenceType1Distance_ = 0;
     onChanged();
     return this;
   }

   private int geofenceType2Entries_ ;
   /**
    * <code>optional uint32 geofence_type2_entries = 5;</code>
    *
    * <pre>
    * Geofence type 2 entries
    * </pre>
    */
   public boolean hasGeofenceType2Entries() {
     return ((bitField0_ & 0x00000010) == 0x00000010);
   }
   /**
    * <code>optional uint32 geofence_type2_entries = 5;</code>
    *
    * <pre>
    * Geofence type 2 entries
    * </pre>
    */
   public int getGeofenceType2Entries() {
     return geofenceType2Entries_;
   }
   /**
    * <code>optional uint32 geofence_type2_entries = 5;</code>
    *
    * <pre>
    * Geofence type 2 entries
    * </pre>
    */
   public Builder setGeofenceType2Entries(int value) {
     bitField0_ |= 0x00000010;
     geofenceType2Entries_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional uint32 geofence_type2_entries = 5;</code>
    *
    * <pre>
    * Geofence type 2 entries
    * </pre>
    */
   public Builder clearGeofenceType2Entries() {
     bitField0_ = (bitField0_ & ~0x00000010);
     geofenceType2Entries_ = 0;
     onChanged();
     return this;
   }

   private int geofenceType2Time_ ;
   /**
    * <code>optional uint32 geofence_type2_time = 6;</code>
    *
    * <pre>
    * Geofence type 2 time (seconds)
    * </pre>
    */
   public boolean hasGeofenceType2Time() {
     return ((bitField0_ & 0x00000020) == 0x00000020);
   }
   /**
    * <code>optional uint32 geofence_type2_time = 6;</code>
    *
    * <pre>
    * Geofence type 2 time (seconds)
    * </pre>
    */
   public int getGeofenceType2Time() {
     return geofenceType2Time_;
   }
   /**
    * <code>optional uint32 geofence_type2_time = 6;</code>
    *
    * <pre>
    * Geofence type 2 time (seconds)
    * </pre>
    */
   public Builder setGeofenceType2Time(int value) {
     bitField0_ |= 0x00000020;
     geofenceType2Time_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional uint32 geofence_type2_time = 6;</code>
    *
    * <pre>
    * Geofence type 2 time (seconds)
    * </pre>
    */
   public Builder clearGeofenceType2Time() {
     bitField0_ = (bitField0_ & ~0x00000020);
     geofenceType2Time_ = 0;
     onChanged();
     return this;
   }

   private int geofenceType2Distance_ ;
   /**
    * <code>optional uint32 geofence_type2_distance = 7;</code>
    *
    * <pre>
    * Geofence type 2 distance (meters)
    * </pre>
    */
   public boolean hasGeofenceType2Distance() {
     return ((bitField0_ & 0x00000040) == 0x00000040);
   }
   /**
    * <code>optional uint32 geofence_type2_distance = 7;</code>
    *
    * <pre>
    * Geofence type 2 distance (meters)
    * </pre>
    */
   public int getGeofenceType2Distance() {
     return geofenceType2Distance_;
   }
   /**
    * <code>optional uint32 geofence_type2_distance = 7;</code>
    *
    * <pre>
    * Geofence type 2 distance (meters)
    * </pre>
    */
   public Builder setGeofenceType2Distance(int value) {
     bitField0_ |= 0x00000040;
     geofenceType2Distance_ = value;
     onChanged();
     return this;
   }
   /**
    * <code>optional uint32 geofence_type2_distance = 7;</code>
    *
    * <pre>
    * Geofence type 2 distance (meters)
    * </pre>
    */
   public Builder clearGeofenceType2Distance() {
     bitField0_ = (bitField0_ & ~0x00000040);
     geofenceType2Distance_ = 0;
     onChanged();
     return this;
   }

   // @@protoc_insertion_point(builder_scope:DailyGeofenceSummary)
 }

 static {
   defaultInstance = new DailyGeofenceSummary(true);
   defaultInstance.initFields();
 }

 // @@protoc_insertion_point(class_scope:DailyGeofenceSummary)
}

private static final com.google.protobuf.Descriptors.Descriptor
 internal_static_DailyGeofenceSummary_descriptor;
private static
 com.google.protobuf.GeneratedMessage.FieldAccessorTable
   internal_static_DailyGeofenceSummary_fieldAccessorTable;

public static com.google.protobuf.Descriptors.FileDescriptor
   getDescriptor() {
 return descriptor;
}
private static com.google.protobuf.Descriptors.FileDescriptor
   descriptor;
static {
 java.lang.String[] descriptorData = {
   "\n\037DailyGeofenceSummaryProto.proto\032\026Event" +
   "HeaderProto.proto\"\360\001\n\024DailyGeofenceSumma" +
   "ry\022\034\n\006header\030\001 \002(\0132\014.EventHeader\022\036\n\026geof" +
   "ence_type1_entries\030\002 \001(\r\022\033\n\023geofence_typ" +
   "e1_time\030\003 \001(\r\022\037\n\027geofence_type1_distance" +
   "\030\004 \001(\r\022\036\n\026geofence_type2_entries\030\005 \001(\r\022\033" +
   "\n\023geofence_type2_time\030\006 \001(\r\022\037\n\027geofence_" +
   "type2_distance\030\007 \001(\r"
 };
 com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
     new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
       public com.google.protobuf.ExtensionRegistry assignDescriptors(
           com.google.protobuf.Descriptors.FileDescriptor root) {
         descriptor = root;
         return null;
       }
     };
 com.google.protobuf.Descriptors.FileDescriptor
   .internalBuildGeneratedFileFrom(descriptorData,
     new com.google.protobuf.Descriptors.FileDescriptor[] {
       EventHeaderProto.getDescriptor(),
     }, assigner);
 internal_static_DailyGeofenceSummary_descriptor =
   getDescriptor().getMessageTypes().get(0);
 internal_static_DailyGeofenceSummary_fieldAccessorTable = new
   com.google.protobuf.GeneratedMessage.FieldAccessorTable(
     internal_static_DailyGeofenceSummary_descriptor,
     new java.lang.String[] { "Header", "GeofenceType1Entries", "GeofenceType1Time", "GeofenceType1Distance", "GeofenceType2Entries", "GeofenceType2Time", "GeofenceType2Distance", });
 EventHeaderProto.getDescriptor();
}

// @@protoc_insertion_point(outer_class_scope)
}
